### PR TITLE
fix #94 by lowering new anon class to new class

### LINKED ISSUE #94: Assertion failure in ResolveType
```d
auto foo()
{
    return new class Bar {};
}   
```

```
core.exception.AssertError@dsymbol/src/dsymbol/conversion/second.d(413): How did this happen?
----------------
??:? _d_assert_msg [0xae661a]
dsymbol/src/dsymbol/conversion/second.d:413 void dsymbol.conversion.second.resolveType(dsymbol.symbol.DSymbol*, ref containers.unrolledlist.UnrolledList!(dsymbol.type_lookup.TypeLookup*, stdx.allocator.mallocator.Mallocator, false, 64uL).UnrolledList, dsymbol.scope_.Scope*, ref dsymbol.modulecache.ModuleCache) [0x8bfe34]
dsymbol/src/dsymbol/conversion/second.d:56 void dsymbol.conversion.second.secondPass(dsymbol.semantic.SemanticSymbol*, dsymbol.scope_.Scope*, ref dsymbol.modulecache.ModuleCache) [0x8be9e3]
dsymbol/src/dsymbol/conversion/second.d:77 void dsymbol.conversion.second.secondPass(dsymbol.semantic.SemanticSymbol*, dsymbol.scope_.Scope*, ref dsymbol.modulecache.ModuleCache) [0x8bea5f]
src/dscanner/analysis/run.d:328 std.container.rbtree.RedBlackTree!(dscanner.analysis.base.Message, " a.line < b.line || (a.line == b.line && a.column < b.column) ", true).RedBlackTree dscanner.analysis.run.analyze(immutable(char)[], const(dparse.ast.Module), const(dscanner.analysis.config.StaticAnalysisConfig), ref dsymbol.modulecache.ModuleCache, const(std.experimental.lexer.TokenStructure!(ubyte, "\x0a    string comment;\x0a    string trailingComment;\x0a\x0a    int opCmp(size_t i) const pure nothrow @safe {\x0a        if (index < i) return -1;\x0a        if (index > i) return 1;\x0a        return 0;\x0a    }\x0a\x0a    int opCmp(ref const typeof(this) other) const pure nothrow @safe {\x0a        return opCmp(other.index);\x0a    }\x0a").TokenStructure)[], bool) [0xa65496]
src/dscanner/analysis/run.d:200 bool dscanner.analysis.run.analyze(immutable(char)[][], const(dscanner.analysis.config.StaticAnalysisConfig), immutable(char)[], ref dparse.lexer.StringCache, ref dsymbol.modulecache.ModuleCache, bool) [0xa650a7]
src/dscanner/main.d:242 _Dmain [0xa53acd]
```

https://github.com/dlang-community/D-Scanner/issues/697

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

File: src/dsymbol/conversion/first.d [hunk 1]
```diff
@@ -1341,7 +1342,42 @@ class InitializerVisitor : ASTVisitor
 
 	// Skip these
 	override void visit(const ArgumentList) {}
-	override void visit(const NewAnonClassExpression) {}
+
+	override void visit(const NewExpression ne)
+	{
+		if (ne.newAnonClassExpression)
+		{
+			(cast() ne).assignExpression = lowerNewAnonToNew(ne);
```
Comment (BBasile) [inline src/dsymbol/conversion/first.d]: This must be in the NewExpression parameters, no as its assignExpression which is used for totaly different things. The DCD PR works for some reasons...
